stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/email_phishing_data.csv
    outs:
    - data/raw/email_phishing_data.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data_given/email_phishing_data.csv
    outs:
    - data/processed/train_email_phishing_data.csv
    - data/processed/test_email_phishing_data.csv

  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
    - data/processed/train_email_phishing_data.csv
    - data/processed/test_email_phishing_data.csv 
    - src/train_and_evaluate.py
    params:
    - estimators.LogisticRegression.params.solver
    - estimators.LogisticRegression.params.l1_ratio
    metrics:
    - report/evaluation_metrices.json:
        cache: false
    - report/params.json:
        cache: false
    outs:
    - saved_models/model.joblib