base:
  project: phisingemail-project
  random_state: 42
  target_col: label

data_source:
  s3_source: data_given/email_phishing_data.csv

load_data:
  raw_dataset_csv: data/raw/email_phishing_data.csv

split_data:
  train_path: data/processed/train_email_phishing_data.csv
  test_path: data/processed/test_email_phishing_data.csv
  test_size: 0.2

estimators:
  LogisticRegression:
    params:
      penalty: l2
      solver: lbfgs
      #l1_ratio: 0.4
      l1_ratio: 0.5
reports:
  params: report/params.json
  evaluation: report/evaluation_metrices.json

model_dir: saved_models